### ISSUE TITLE
@property \AmoCRM\Models\WebHooks $webhooks

### ISSUE THREAD

**Issue by mauztor** [dotzero/yii2-amocrm#2]
В классе Client 
`@property \AmoCRM\Models\WebHooks $webhooks`
необходимо исправить на 
`@property \AmoCRM\Models\WebHooks $web_hooks`

**Comment by dotzero** [comment]
Я как раз принял PullRequest который исправляет этот баг. https://github.com/dotzero/amocrm-php/pull/29 обновите библиотеки и можно использовать `$webhooks` как и написано в документации.
